// src/utils/estados-cidades.ts
export const estadosECidades: Record<string, string[]> = {
  AC: ["Rio Branco", "Cruzeiro do Sul", "Sena Madureira"],
  AL: ["Maceió", "Arapiraca", "Palmeira dos Índios"],
  AM: ["Manaus", "Parintins", "Itacoatiara"],
  AP: ["Macapá", "Santana"],
  BA: ["Salvador", "Feira de Santana", "Ilhéus"],
  CE: ["Fortaleza", "Caucaia", "Juazeiro do Norte"],
  DF: ["Brasília"],
  ES: ["Vitória", "Vila Velha", "Serra"],
  GO: ["Goiânia", "Aparecida de Goiânia", "Anápolis"],
  MA: ["São Luís", "Imperatriz"],
  MG: ["Belo Horizonte", "Uberlândia", "Contagem"],
  MS: ["Campo Grande", "Dourados"],
  MT: ["Cuiabá", "Várzea Grande"],
  PA: ["Belém", "Ananindeua"],
  PB: ["João Pessoa", "Campina Grande"],
  PE: ["Recife", "Olinda", "Caruaru"],
  PI: ["Teresina", "Parnaíba"],
  PR: ["Curitiba", "Londrina", "Maringá"],
  RJ: ["Rio de Janeiro", "Niterói", "Nova Iguaçu"],
  RN: ["Natal", "Mossoró"],
  RO: ["Porto Velho", "Ji-Paraná"],
  RR: ["Boa Vista"],
  RS: ["Porto Alegre", "Caxias do Sul", "Pelotas"],
  SC: ["Florianópolis", "Joinville", "Blumenau"],
  SE: ["Aracaju", "Nossa Senhora do Socorro"],
  SP: ["São Paulo", "Campinas", "Santos"],
  TO: ["Palmas", "Araguaína"],
};
